### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by karambaq** [pagankeymaster/nvim-config#7]
Hey, really really wonderful config! 
I think I didn't see anything similar, great job! 

I really want my neovim too look that fancy but unfortunately I don't know Lua and neovim config system and I faced a couple of errors while trying to copy your config.
So I have a couple of questions:

1) How can I change theme globally which provide nvim-colo, in which file I should add something? I've tried change `fallback` theme to something else but he can't find them.
2) feline isn't starting, how can I enable it?
3) When I open directory, and then select file using ranger - this happens:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/14233969/227322196-a085a3a2-e833-4595-8112-e048312bf866.png">

Thanks in advance!

**Comment by dharmx** [comment]
Plugin specs are not allowed there. All those plugin names in `setup` will be excluded (They will be disabled). I did this because I found navigating to the specific plugin files and commenting out plugins quite cumbersome. And, this will help if any config error occurs.

```lua
-- I guess you can interpret setup as exclude.
require("dharmx.plug").setup({
  "simrat39/symbols-outline.nvim",
  "sheerun/vim-polyglot",
  "andweeb/presence.nvim",
  "rktjmp/paperplanes.nvim",
  "nvim-treesitter/nvim-tree-docs",
  "windwp/nvim-ts-autotag",
  "echasnovski/mini.indentscope",
  "nvim-tree/nvim-tree.lua",
  "hrsh7th/cmp-nvim-lua",
})
```

And, only strings are allowed there. If you want to add plugins then either add that whichkey table to one of the files [here](https://github.com/dharmx/nvim/tree/main/lua/dharmx/plug/spec) or, create a new file there and return a table similar to the following.

```lua
-- Inside ~/.config/nvim/lua/dharmx/plug/spec/others.lua
-- Name can be anything because all files under ~/.config/nvim/lua/dharmx/plug/spec
-- will be sourced automatically.

return {
  {
    "folke/whick-key.nvim",
    ...
  }
}
```

As, for the ranger thing I am not too sure. That error seems to be coming from my [telescope-mdia.nvim](https://github.com/dharmx/telescope-media.nvim) plugin though, which is confusing.

**Comment by dharmx** [comment]
Themes are pulled from the [nvim-colo](https://github.com/dharmx/nvim-colo/) plugin. You can find all available themes [here](https://github.com/dharmx/nvim-colo/tree/dev/lua/colo/themes). And, from Neovim you can call `:ColoTele`. And, you can use `:Colo radium_dark` for setting the theme of your choice.
The colo config can be found [here](https://github.com/dharmx/nvim/blob/main/lua/dharmx/plug/config/core/colo.lua). It is recommended to use `:Colo` and `:ColoTele` to only browse the themes and the config to set the theme.

**Comment by dharmx** [comment]
Did a push. Feline should work now.

**Comment by dharmx** [comment]
Alright, closing this. Feel free to reopen if you need anything.

**Comment by karambaq** [comment]
Thank you!
